language: python
matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    python: '2.7'
    language: generic
    env:
      - BUILD_SDIST=true
  - os: osx
    osx_image: xcode11.3
    python: '3.5'
    language: generic
  - os: osx
    osx_image: xcode11.3
    python: '3.6'
    language: generic
  - os: osx
    osx_image: xcode11.3
    python: '3.7'
    language: generic  
install:
  - brew install openssl && brew install swig
  - LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" SWIG_FEATURES="-I$(brew --prefix openssl)/include" pip install m2crypto==0.32.0 --user
  - pip install -r requirements.txt --user
  - sudo mkdir /usr/local/man
  - sudo chmod a+w /usr/local/man
  - pip install mock --user
script:
  - python tests/__init__.py
before_deploy: 
  - echo $TRAVIS_TAG | sed 's/^.//' > version.txt
  - echo $PATH
  - export PATH=/Users/travis/Library/Python/2.7/bin:$PATH

deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  user: qta
  password:
    secure: llUKO+kalJKwArwsN/fmgasdLb+toMD6x4ClZ0yXnaS3C+Cwmuw3KRKZvX03GmAPYCiz/tpMsU0GrvqUk3PZouRI1AxiZN+AnGLmfi6HtCPAgRJhKoqJAyZttMWOVCrxtXnq6fLjcwBswmR5ryj63VjtDCgsNN0AVnhFyTJJtKUuLQxGNSUMOphcpFaKb9YctMoQqbQWGSwGWbiKVaElAk7PSaEeKo75ICt4abc1nzxBrLU2SNKH72HQyZKcslWka/h9p0VOfB3vAoY3CSc0xK2mKY+4JOVnxCs5l3lSRcFYMzs9taJQgYu2Xl0YY0FvMSh3453MgTMoQLhX2Yi6AovSHBU1Jh2VlikvYEljrIcQyqzZ4iBc0OQg1FCH8JD1vXnIn+ybHpR0qyerU9jbz5+Ux1SxkeqZA0H5mI1JVf6EFadKxjI/+l8437cU7+yU+loNRDPRO8IQ4YzN6tCfDlifgaAEOYs3zpzsbL2/B/Dtl1YUSMSqt8Zr5LJygeWfXvZ+KgYpJc330pyw9r9lgw1qls0ZfYZry6sLyVc5Zl34OfIDgugGvxEZdfQR0SbmzYBHai1xasP4wvYJh1jsg0bVwr6yAJyfLu+Z5pIquTNOa/K0m5kkXH0pS/FWn60tuI/+QyIEVE0Tcf23TfrFB33RGmoaPuL/w0JAI3ee4bM=
  distributions: sdist
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
