language: python
matrix:
  include:
  - os: osx
    python: '2.7'
    language: generic
    env:
      - BUILD_SDIST=true
install:
  - pip install -r requirements.txt --user
  - sudo mkdir /usr/local/man
  - sudo chmod a+w /usr/local/man
  - pip install mock --user
script:
  - python tests/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  password:
    secure: $KEYSTORE_PASSWD
  distributions: sdist
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
