language: python
matrix:
  include:
  - os: osx
    python: '2.7'
    language: generic
    env: BUILD_SDIST=true
install:
  - pip install -r requirements.txt --user
  - sudo mkdir /usr/local/man
  - sudo chmod a+w /usr/local/man
  - pip install mock --user
script:
  - python tests/__init__.py
before_deploy: "echo $TRAVIS_TAG | sed 's/^.//' > version.txt"
deploy:
  skip_cleanup: true
  provider: pypi
  user: "qta"
  password: 
    secure: Q5Ykk4YdOG/yFu0rHS+ujM2dHCckbfsjERWtc++qAdrM1oY0cBG8+T+MRGNIng0GaOPS/3ERYuepzjQxcqIL17CsE52y8w2A5fWzOYKDPVHMWIdfMR8NRNsWcGwnAApkFtTuKMXRN6TmUnkbpcIxpa59ktq850/CcTSELXRPf3am+tA22yDXEr/IXz5eB1sElrXggPFwB/rSjO+Vq73fXhaQLlAFUK+B0BLcQDqNGyHGtyxFDfKXG9WhGSKi1222rbGHRPJrBeumqxFyasY3Gd8YYNkJiKUd4+O1HPZMt/Bx2EzVB1yizeoXr67bddDhIA2lLJUbMJe7YFH2zXYiZNWBVPlV2mMUuzbPZ0IqWrByiutxPyiU3tKrwrvW0f1e/XedbELCRLhIiI5wCyTHSLIBBJZUlUly3e4YQhRMTeOrVlPLVo3rjkB4BHP0OzFMfd6CXKYner5Lh9jKlyOCpdeDRST+lD7t4FSVCFofYtyUdMq4HYig/j+VQRu/wpIVlkrBqb0SkbWLgVTbcFSK1Ik6wXoV9P90w7DqZn1vv5Bfo+HQez1uQj5G7JCTqfz5gcDDx/UPl/BeePkAzlOJeKduqoh77cjtP9NTMqu5siMGHO72bsmtD0+p1jlzHyG18jQ0uHMVlAtQaMUChofsS48kXoVIgtLMNHwiJrbqTO0=
  distributions: sdist 
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
